# Generated by Django 3.1.2 on 2020-11-16 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Statistique', '0005_auto_20201115_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('Utilisateur_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=10)),
                ('datej', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donateur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Admin.utilisateur')),
                ('dateNais', models.DateField()),
            ],
            bases=('Admin.utilisateur',),
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('hopital_id', models.AutoField(primary_key=True, serialize=False)),
                ('nomH', models.CharField(max_length=25)),
                ('adresse', models.CharField(max_length=25)),
                ('num_compte', models.CharField(max_length=25)),
                ('gouvernorat_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Statistique.gouvernorat')),
            ],
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('Utilisateur_id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.FloatField()),
                ('dateD', models.DateField(auto_now_add=True)),
                ('hopital_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.hopital')),
                ('donateur_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.donateur')),
            ],
        ),
        migrations.AddField(
            model_name='hopital',
            name='donateur_FK',
            field=models.ManyToManyField(through='Admin.Don', to='Admin.Donateur'),
        ),
    ]
