# Generated by Django 3.1.2 on 2020-11-13 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Don', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('hopital_id', models.AutoField(primary_key=True, serialize=False)),
                ('nomH', models.CharField(max_length=25)),
                ('adresse', models.CharField(max_length=25)),
                ('num_compte', models.CharField(max_length=25)),
                ('gouvernorat_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Don.gouvernorat')),
            ],
        ),
    ]
