# Generated by Django 3.1.2 on 2020-11-13 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Don', '0002_hopital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('Utilisateur_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=10)),
                ('datej', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donateur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Don.utilisateur')),
                ('dateNais', models.DateField()),
            ],
            bases=('Don.utilisateur',),
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('Utilisateur_id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.FloatField()),
                ('dateD', models.DateField(auto_now_add=True)),
                ('hopital_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Don.hopital')),
                ('donateur_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Don.donateur')),
            ],
        ),
        migrations.AddField(
            model_name='hopital',
            name='donateur_FK',
            field=models.ManyToManyField(through='Don.Don', to='Don.Donateur'),
        ),
    ]
