# Generated by Django 3.1.2 on 2020-11-16 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Don', '0004_auto_20201113_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donateur',
            name='utilisateur_ptr',
        ),
        migrations.RemoveField(
            model_name='hopital',
            name='donateur_FK',
        ),
        migrations.RemoveField(
            model_name='hopital',
            name='gouvernorat_FK',
        ),
        migrations.DeleteModel(
            name='Don',
        ),
        migrations.DeleteModel(
            name='Donateur',
        ),
        migrations.DeleteModel(
            name='Hopital',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
