# Generated by Django 3.1.2 on 2020-11-13 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gouvernorat',
            fields=[
                ('gouvernorat_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('statistiqu_id', models.AutoField(primary_key=True, serialize=False)),
                ('cas_positif', models.IntegerField()),
                ('deces', models.IntegerField()),
                ('guerison', models.IntegerField()),
                ('cas_actif', models.IntegerField()),
                ('datest', models.DateField()),
                ('gouvernorat_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Statistique.gouvernorat')),
            ],
        ),
    ]
