# Generated by Django 3.1.2 on 2020-11-13 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Statistique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gouvernorat',
            name='nom',
        ),
    ]
