# Generated by Django 3.1.2 on 2020-11-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistique', '0002_remove_gouvernorat_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='gouvernorat',
            name='nom',
            field=models.CharField(default=4, max_length=25),
            preserve_default=False,
        ),
    ]
