# Generated by Django 3.1.2 on 2020-11-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistique', '0003_gouvernorat_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistique',
            name='datest',
            field=models.CharField(max_length=10),
        ),
    ]
