# Generated by Django 3.1.2 on 2020-11-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistique', '0004_auto_20201115_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistique',
            name='cas_actif',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='cas_positif',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='deces',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='guerison',
            field=models.CharField(max_length=10),
        ),
    ]
